import "@/styles/globals.css";
import "leaflet/dist/leaflet.css";
import React from "react";
import { useRouter } from "next/router";
import { AppCacheProvider } from "@mui/material-nextjs/v13-pagesRouter";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { Roboto } from "next/font/google";
import Layout from "@/components/layout";
import useBearStore from "@/store/useBearStore";
import Head from "next/head";
import ProtectedRoute from "@/utils/protectedRoute";
import PublicRoute from "@/utils/publicRoute";
import { AuthProvider } from "@/contexts/AuthContext";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

const theme = createTheme({
  palette: {},
  typography: {
    fontFamily: roboto.style.fontFamily,
  },
});

export default function App({ Component, pageProps, props }) {
  const router = useRouter();
  const [loading, setLoading] = React.useState(false);
  const setAppName = useBearStore((state) => state.setAppName);
  const pageName = router.pathname;

  const publicRoutes = ["/register", "/login"];
  const isPublicRoute = publicRoutes.includes(pageName);

  React.useEffect(() => {
    console.log("App load", pageName, router.query);
    setLoading(true);
    setAppName("Say Hi");
    setLoading(false);
  }, [router, pageName]);

  return (
    <React.Fragment>
      <Head>
        <title>{`Application`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppCacheProvider {...props}>
        <ThemeProvider theme={theme}>
          <AuthProvider>
            {isPublicRoute ? (
              <PublicRoute>
                <Component {...pageProps} />
              </PublicRoute>
            ) : (
              <Layout>
                <ProtectedRoute>
                  <Component {...pageProps} />
                </ProtectedRoute>
              </Layout>
            )}
          </AuthProvider>
        </ThemeProvider>
      </AppCacheProvider>
    </React.Fragment>
  );
}